---
galaxy_info:
  author: JacobPEvans
  description: Deploy Cribl Edge and Stream on Docker Swarm with HA
  license: Apache-2.0
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - cribl
    - docker
    - swarm
    - logging
    - syslog
    - observability

dependencies: []
  # community.docker collection is specified in requirements.yml
