---
- name: Reload haproxy
  ansible.builtin.systemd:
    name: "{{ haproxy_service_name }}"
    state: reloaded

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
