---
# VM group variables
# These settings apply to all regular VMs (SSH connection)

ansible_user: debian
ansible_python_interpreter: /usr/bin/python3

# SSH connection settings
ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
